const types = {
    ADD_CLIENT: '@@app/ADD_CLIENT',
    ADD_CLIENT_START: '@@app/ADD_CLIENT_START',
    SERVER_CLIENTS_COUNT: '@@ws/SERVER_CLIENTS_COUNT',
    REMOVE_CLIENT: '@app/REMOVE_CLIENT',
    CLIENT_MSG: '@app/CLIENT_MSG',
    SERVER_CLIENT_MSG: '@@ws/SERVER_CLIENT_MSG',
};


export default types;
